### ISSUE TITLE
[Errno 2] No such file or directory: '/home/jing-zhang/jing_file/vgg16-397923af.pth'

### ISSUE THREAD

**Issue by 18718277909** [JingZhang617/Scribble_Saliency#13]
Hi， thanks for your contribution, but when I run the train.py, it has a error:[Errno 2] No such file or directory: '/home/jing-zhang/jing_file/vgg16-397923af.pth', when I change it ,it will has an error: 'odict_keys' object is not subscriptable

**Comment by JingZhang617** [comment]
Hi this is due to pytorch version difference. Please change:
def _initialize_weights(self, pre_train):
        keys = pre_train.keys()
to:
def _initialize_weights(self, pre_train):
        keys = list(pre_train.keys())

in the vgg.py file.

**Comment by 18718277909** [comment]
> Hi this is due to pytorch version difference. Please change:
> def _initialize_weights(self, pre_train):
> keys = pre_train.keys()
> to:
> def _initialize_weights(self, pre_train):
> keys = list(pre_train.keys())
> 
> in the vgg.py file.

thanks for your reply，I successfully solved the previous problem, but when I run it again, it give me a new error: 
 File "<string>", line 1, in <module>
  File "C:\Users\admin\.conda\envs\pytorch\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\admin\.conda\envs\pytorch\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\admin\.conda\envs\pytorch\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\admin\.conda\envs\pytorch\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\admin\.conda\envs\pytorch\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\admin\.conda\envs\pytorch\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\admin\.conda\envs\pytorch\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\YangYi\Scribble_Saliency-master\train.py", line 11, in <module>
    from utils import clip_gradient,adjust_lr
  File "G:\YangYi\Scribble_Saliency-master\utils.py", line 11, in <module>
    fx = Variable(torch.from_numpy(fx)).cuda()
  File "C:\Users\admin\.conda\envs\pytorch\lib\site-packages\torch\cuda\__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
Traceback (most recent call last):
  File "G:/YangYi/Scribble_Saliency-master/train.py", line 140, in <module>
    train(train_loader, model, optimizer, epoch)
  File "G:/YangYi/Scribble_Saliency-master/train.py", line 86, in train
    for i, pack in enumerate(train_loader, start=1):
  File "C:\Users\admin\.conda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "C:\Users\admin\.conda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\admin\.conda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "C:\Users\admin\.conda\envs\pytorch\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\admin\.conda\envs\pytorch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\admin\.conda\envs\pytorch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\admin\.conda\envs\pytorch\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\admin\.conda\envs\pytorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

Can you help me again,  thank you very much.
